

#The below simulated data does not include hdop.

# beta1_true  <- 1.5  
# beta2_true  <- 1
# sigma_true <- 20
# sigma2_true <- 10
# dt <- 10/1440 days

# By running this code, I get: 
# > p_hat
#    beta1     beta2     sigma    sigma2 
# 1.768372  1.069901 19.543344 10.203571 




library(MASS)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)



beta1_true  <- 1.8     # horizontal OU damping
beta2_true  <- 0.8     # vertical OU damping
sigma_true  <- 20      # horizontal process noise
sigma2_true <- 10      # vertical process noise

s1 <- sigma_true^2
s2 <- sigma_true^2
s3 <- sigma2_true^2



N  <- 5000                     # number of time steps
dt <- 15 / (24*60)             # 10 minutes in days
time_vec <- seq(0, by = dt, length.out = N)

# Latent state: (x, vx, y, vy, depth, vdepth)
X <- matrix(0, nrow = N, ncol = 6)
X[1,] <- c(0, 0, 0, 0, -50, 0)




makeT <- function(b1, b2, dt) {
  T <- matrix(0, 6, 6)
  e1 <- exp(-b1 * dt)
  e2 <- exp(-b2 * dt)

  T[1,1] <- 1
  T[2,2] <- e1
  T[1,2] <- (1 - e1)/b1

  T[3,3] <- 1
  T[4,4] <- e1
  T[3,4] <- (1 - e1)/b1

  T[5,5] <- 1
  T[6,6] <- e2
  T[5,6] <- (1 - e2)/b2

  T
}

makeQ <- function(b1, b2, s1, s2, s3, dt) {

  e1  <- exp(-b1 * dt)
  e2  <- exp(-2*b1*dt)
  q11_1 <- (dt - 2*(1-e1)/b1 + (1-e2)/(2*b1)) / b1^2
  q13_1 <- ((1-e1) - (1-e2)/2) / b1^2
  q33_1 <- (1-e2)/(2*b1)

  e1v  <- exp(-b2 * dt)
  e2v  <- exp(-2*b2*dt)
  q11_2 <- (dt - 2*(1-e1v)/b2 + (1-e2v)/(2*b2)) / b2^2
  q13_2 <- ((1-e1v) - (1-e2v)/2) / b2^2
  q33_2 <- (1-e2v)/(2*b2)

  Q <- matrix(0, 6, 6)

  Q[1,1] <- s1*q11_1
  Q[2,2] <- s1*q33_1
  Q[1,2] <- Q[2,1] <- s1*q13_1

  Q[3,3] <- s2*q11_1
  Q[4,4] <- s2*q33_1
  Q[3,4] <- Q[4,3] <- s2*q13_1

  Q[5,5] <- s3*q11_2
  Q[6,6] <- s3*q33_2
  Q[5,6] <- Q[6,5] <- s3*q13_2

  Q
}

Tmat <- makeT(beta1_true, beta2_true, dt)
Qmat <- makeQ(beta1_true, beta2_true, s1, s2, s3, dt)


for (i in 2:N) {
  X[i,] <- Tmat %*% X[i-1,] + MASS::mvrnorm(1, rep(0,6), Qmat)
}



set.seed(123)
obs_type <- rbinom(N, 1, 0.7)   # 70% depth-only, 30% xy-only

obs_x     <- rep(NA, N)
obs_y     <- rep(NA, N)
obs_depth <- rep(NA, N)

for (i in 1:N) {
  if (obs_type[i] == 1) {
    obs_depth[i] <- X[i,5]
  } else {
    obs_x[i] <- X[i,1]
    obs_y[i] <- X[i,3]
  }
}

sim_data <- data.frame(
  time  = ymd_hms("2020-01-01 00:00:00") + time_vec*86400,
  x     = obs_x,
  y     = obs_y,
  depth = obs_depth
)


aug <- sim_data %>%
  mutate(
    Time = as.numeric(difftime(time, min(time), units = "days")) + 1,
    hasObs = !is.na(x) | !is.na(y) | !is.na(depth),
    orig_index = seq_len(n())
  )



makeT_R <- function(b1, b2, delta) {
  ebd1 <- exp(-b1 * delta)
  ebd2 <- exp(-b2 * delta)

  T <- matrix(0, 6, 6)
  T[1,1] <- 1; T[2,2] <- ebd1; T[1,2] <- (1 - ebd1)/b1
  T[3,3] <- 1; T[4,4] <- ebd1; T[3,4] <- (1 - ebd1)/b1
  T[5,5] <- 1; T[6,6] <- ebd2; T[5,6] <- (1 - ebd2)/b2
  T
}

makeQ_R <- function(b1, b2, s1, s2, s3, delta) {
  ebd1  <- exp(-b1 * delta)
  e2bd1 <- exp(-2*b1*delta)
  q11_1 <- (delta - 2*(1-ebd1)/b1 + (1-e2bd1)/(2*b1)) / b1^2
  q13_1 <- ((1-ebd1) - (1-e2bd1)/2) / b1^2
  q33_1 <- (1-e2bd1)/(2*b1)

  ebd2  <- exp(-b2 * delta)
  e2bd2 <- exp(-2*b2*delta)
  q11_2 <- (delta - 2*(1-ebd2)/b2 + (1-e2bd2)/(2*b2)) / b2^2
  q13_2 <- ((1-ebd2) - (1-e2bd2)/2) / b2^2
  q33_2 <- (1-e2bd2)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}



CTCRW_filter <- function(y, beta1_vec, beta2_vec,
                         s1, s2, s3, delta, a, P) {

  N <- nrow(y)

  Z_full <- matrix(0, 3, 6)
  Z_full[1,1] <- 1
  Z_full[2,3] <- 1
  Z_full[3,5] <- 1

  Hmat <- matrix(0, N, 3)   # ZERO measurement error

  a_f <- matrix(NA, N, 6)
  P_f <- vector("list", N)
  a_p <- matrix(NA, N, 6)
  P_p <- vector("list", N)

  aest <- a
  Pest <- P
  ll <- 0

  for (i in 1:N) {

    b1_i <- beta1_vec[i]
    b2_i <- beta2_vec[i]

    Tmat <- makeT_R(b1_i, b2_i, delta[i])
    Qmat <- makeQ_R(b1_i, b2_i, s1, s2, s3, delta[i])

    a_pred <- Tmat %*% aest
    P_pred <- Tmat %*% Pest %*% t(Tmat) + Qmat

    a_p[i,]  <- as.numeric(a_pred)
    P_p[[i]] <- P_pred

    obs_idx <- which(!is.na(y[i, ]))

    if (length(obs_idx) == 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    Z_i <- Z_full[obs_idx, , drop = FALSE]

    Fmat <- Z_i %*% Pest %*% t(Z_i)
    v <- y[i, obs_idx] - Z_i %*% aest

    invF <- solve(Fmat)
    ll <- ll - 0.5 * (log(det(Fmat)) + t(v) %*% invF %*% v)

    K <- Tmat %*% Pest %*% t(Z_i) %*% invF

    aest <- a_pred + K %*% v
    Pest <- Tmat %*% Pest %*% t(Tmat - K %*% Z_i) + Qmat

    a_f[i,]  <- as.numeric(aest)
    P_f[[i]] <- Pest
  }

  list(ll = ll, a_f = a_f, P_f = P_f, a_p = a_p, P_p = P_p)
}




CTCRW_smoother <- function(filter_out, beta1_vec, beta2_vec,
                           s1, s2, s3, delta) {

  N <- nrow(filter_out$a_f)
  a_s <- filter_out$a_f
  P_s <- filter_out$P_f

  for (i in (N-1):1) {

    b1_i <- beta1_vec[i+1]
    b2_i <- beta2_vec[i+1]

    Tmat <- makeT_R(b1_i, b2_i, delta[i+1])

    a_f_i   <- filter_out$a_f[i,]
    a_p_ip1 <- filter_out$a_p[i+1,]
    P_f_i   <- filter_out$P_f[[i]]
    P_p_ip1 <- filter_out$P_p[[i+1]]

    J <- tryCatch(P_f_i %*% t(Tmat) %*% solve(P_p_ip1), error = function(e) NULL)

    if (is.null(J)) next

    a_s[i,]  <- a_f_i + J %*% (a_s[i+1,] - a_p_ip1)
    P_s[[i]] <- P_f_i + J %*% (P_s[[i+1]] - P_p_ip1) %*% t(J)
  }

  list(a_s = a_s, P_s = P_s)
}




neg_loglikelihood <- function(params, data_aug) {

  beta1  <- exp(params["beta1"])
  beta2  <- exp(params["beta2"])
  sigma  <- exp(params["sigma"])
  sigma2 <- exp(params["sigma2"])

  y   <- as.matrix(data_aug[, c("x","y","depth")])
  delta <- c(diff(data_aug$Time), 1)

  s1 <- sigma^2
  s2 <- sigma^2
  s3 <- sigma2^2

  beta1_vec <- rep(beta1, nrow(data_aug))
  beta2_vec <- rep(beta2, nrow(data_aug))

  first_obs <- which(!is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3]))[1]

  a <- c(
    ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
    ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
    ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
  )
  P <- diag(6) * 1e2

  filt <- CTCRW_filter(
    y         = y,
    beta1_vec = beta1_vec,
    beta2_vec = beta2_vec,
    s1        = s1,
    s2        = s2,
    s3        = s3,
    delta     = delta,
    a         = a,
    P         = P
  )

  -filt$ll
}




params_start <- c(
  beta1  = log(0.3),
  beta2  = log(0.2),
  sigma  = log(15),
  sigma2 = log(8)
)

fit <- optim(
  par      = params_start,
  fn       = neg_loglikelihood,
  data_aug = aug,
  method   = "L-BFGS-B",
  control  = list(trace = 1, maxit = 1000)
)

p_hat <- exp(fit$par)
p_hat




beta1_hat <- p_hat["beta1"]
beta2_hat <- p_hat["beta2"]
sigma_hat <- p_hat["sigma"]
sigma2_hat <- p_hat["sigma2"]

y <- as.matrix(aug[, c("x","y","depth")])
delta <- c(diff(aug$Time), 1)

s1 <- sigma_hat^2
s2 <- sigma_hat^2
s3 <- sigma2_hat^2

beta1_vec <- rep(beta1_hat, nrow(aug))
beta2_vec <- rep(beta2_hat, nrow(aug))

first_obs <- which(!is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3]))[1]

a0 <- c(
  ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
  ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
  ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
)
P0 <- diag(6) * 1e2

filt <- CTCRW_filter(
  y         = y,
  beta1_vec = beta1_vec,
  beta2_vec = beta2_vec,
  s1        = s1,
  s2        = s2,
  s3        = s3,
  delta     = delta,
  a         = a0,
  P         = P0
)

smth <- CTCRW_smoother(
  filter_out = filt,
  beta1_vec  = beta1_vec,
  beta2_vec  = beta2_vec,
  s1         = s1,
  s2         = s2,
  s3         = s3,
  delta      = delta
)

aug$mu_x     <- smth$a_s[,1]
aug$mu_y     <- smth$a_s[,3]
aug$mu_depth <- smth$a_s[,5]




ggplot(aug, aes(x = x, y = y)) +
  geom_point(color = "grey70", alpha = 0.4) +
  geom_path(aes(x = mu_x, y = mu_y), color = "blue") +
  coord_equal() +
  theme_minimal()


ggplot(aug, aes(x = time)) +
  geom_point(aes(y = depth), color = "grey70", alpha = 0.4) +
  geom_line(aes(y = mu_depth), color = "blue") +
  theme_minimal()


plot_ly() %>%
  add_markers(data = aug, x = ~x, y = ~y, z = ~depth,
              marker = list(size = 2, color = "gray", opacity = 0.4)) %>%
  add_lines(data = aug, x = ~mu_x, y = ~mu_y, z = ~mu_depth,
            line = list(color = "blue", width = 4)) %>%
  layout(scene = list(zaxis = list(autorange = "reversed")))








######################################


#The below simulated data includes hdop.






#beta1_true <- 1.8  
#beta2_true <- 0.8
#tau1_true <- 30  
#tau2_true <- 10
#dt <- 15/1440 days




# By running this code, I get: 
# > p_hat
#        beta1        beta2        sigma       sigma2         tau1         tau2 
# 4.205087e+05 1.000828e+00 1.153719e+07 1.153263e+01 9.762888e+00 1.009803e+01 








library(MASS)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
set.seed(123)


# TRUE PARAMETERS
beta1_true  <- 1.8     # horizontal OU damping
beta2_true  <- 0.8     # vertical OU damping
sigma_true  <- 20      # horizontal process noise SD
sigma2_true <- 10      # vertical process noise SD

tau1_true <- 30        # horizontal measurement error SD (meters)
tau2_true <- 10        # depth measurement error SD (meters)

s1 <- sigma_true^2
s2 <- sigma_true^2
s3 <- sigma2_true^2

# LATENT CTCRW PROCESS
N  <- 5000
dt <- 15 / (24*60)   # 15 minutes in days
time_vec <- seq(0, by = dt, length.out = N)

# State vector: (x, vx, y, vy, depth, vdepth)
X <- matrix(0, nrow = N, ncol = 6)
X[1,] <- c(0, 0, 0, 0, -50, 0)

makeT <- function(b1, b2, dt) {
  T <- matrix(0, 6, 6)
  e1 <- exp(-b1 * dt)
  e2 <- exp(-b2 * dt)
  T[1,1] <- 1; T[2,2] <- e1; T[1,2] <- (1 - e1)/b1
  T[3,3] <- 1; T[4,4] <- e1; T[3,4] <- (1 - e1)/b1
  T[5,5] <- 1; T[6,6] <- e2; T[5,6] <- (1 - e2)/b2
  T
}

makeQ <- function(b1, b2, s1, s2, s3, dt) {
  e1  <- exp(-b1 * dt)
  e2  <- exp(-2*b1*dt)
  q11_1 <- (dt - 2*(1-e1)/b1 + (1-e2)/(2*b1)) / b1^2
  q13_1 <- ((1-e1) - (1-e2)/2) / b1^2
  q33_1 <- (1-e2)/(2*b1)

  e1v  <- exp(-b2 * dt)
  e2v  <- exp(-2*b2*dt)
  q11_2 <- (dt - 2*(1-e1v)/b2 + (1-e2v)/(2*b2)) / b2^2
  q13_2 <- ((1-e1v) - (1-e2v)/2) / b2^2
  q33_2 <- (1-e2v)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

Tmat <- makeT(beta1_true, beta2_true, dt)
Qmat <- makeQ(beta1_true, beta2_true, s1, s2, s3, dt)

for (i in 2:N) {
  X[i,] <- Tmat %*% X[i-1,] + MASS::mvrnorm(1, rep(0,6), Qmat)
}

# OBSERVATIONS WITH MEASUREMENT ERROR + hdop
obs_type <- rbinom(N, 1, 0.7)   # 70% depth-only, 30% xy-only

obs_x     <- rep(NA, N)
obs_y     <- rep(NA, N)
obs_depth <- rep(NA, N)
hdop      <- rep(NA, N)

for (i in 1:N) {
  if (obs_type[i] == 1) {
    # depth-only observation
    obs_depth[i] <- X[i,5] + rnorm(1, 0, tau2_true)
    hdop[i]      <- NA
  } else {
    # xy-only observation
    obs_x[i] <- X[i,1] + rnorm(1, 0, tau1_true)
    obs_y[i] <- X[i,3] + rnorm(1, 0, tau1_true)
    hdop[i]  <- runif(1, 1, 25)  # hdop between 1 and 25
  }
}

sim_data <- data.frame(
  time  = ymd_hms("2020-01-01 00:00:00") + time_vec*86400,
  x     = obs_x,
  y     = obs_y,
  depth = obs_depth,
  hdop  = hdop
)

aug <- sim_data %>%
  mutate(
    Time = as.numeric(difftime(time, min(time), units = "days")) + 1,
    hasObs = !is.na(x) | !is.na(y) | !is.na(depth),
    orig_index = seq_len(n())
  )

summary(aug[, c("x","y","depth","hdop","Time")])


makeT_R <- function(b1, b2, delta) {
  ebd1 <- exp(-b1 * delta)
  ebd2 <- exp(-b2 * delta)
  T <- matrix(0, 6, 6)
  T[1,1] <- 1; T[2,2] <- ebd1; T[1,2] <- (1 - ebd1)/b1
  T[3,3] <- 1; T[4,4] <- ebd1; T[3,4] <- (1 - ebd1)/b1
  T[5,5] <- 1; T[6,6] <- ebd2; T[5,6] <- (1 - ebd2)/b2
  T
}

makeQ_R <- function(b1, b2, s1, s2, s3, delta) {
  ebd1  <- exp(-b1 * delta)
  e2bd1 <- exp(-2*b1*delta)
  q11_1 <- (delta - 2*(1-ebd1)/b1 + (1-e2bd1)/(2*b1)) / b1^2
  q13_1 <- ((1-ebd1) - (1-e2bd1)/2) / b1^2
  q33_1 <- (1-e2bd1)/(2*b1)

  ebd2  <- exp(-b2 * delta)
  e2bd2 <- exp(-2*b2*delta)
  q11_2 <- (delta - 2*(1-ebd2)/b2 + (1-e2bd2)/(2*b2)) / b2^2
  q13_2 <- ((1-ebd2) - (1-e2bd2)/2) / b2^2
  q33_2 <- (1-e2bd2)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

CTCRW_filter <- function(y, Hmat, beta1_vec, beta2_vec,
                         s1, s2, s3, delta, a, P) {

  N <- nrow(y)

  Z_full <- matrix(0, 3, 6)
  Z_full[1,1] <- 1
  Z_full[2,3] <- 1
  Z_full[3,5] <- 1

  a_f <- matrix(NA, N, 6)
  P_f <- vector("list", N)
  a_p <- matrix(NA, N, 6)
  P_p <- vector("list", N)

  aest <- a
  Pest <- P
  ll <- 0

  for (i in 1:N) {

    b1_i <- beta1_vec[i]
    b2_i <- beta2_vec[i]

    Tmat <- makeT_R(b1_i, b2_i, delta[i])
    Qmat <- makeQ_R(b1_i, b2_i, s1, s2, s3, delta[i])

    a_pred <- Tmat %*% aest
    P_pred <- Tmat %*% Pest %*% t(Tmat) + Qmat

    a_p[i,]  <- as.numeric(a_pred)
    P_p[[i]] <- P_pred

    obs_idx <- which(!is.na(y[i, ]))

    if (length(obs_idx) == 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    Z_i <- Z_full[obs_idx, , drop = FALSE]
    H_i <- diag(Hmat[i, obs_idx], length(obs_idx))

    v <- y[i, obs_idx] - Z_i %*% aest
    Fmat <- Z_i %*% Pest %*% t(Z_i) + H_i

    detF <- det(Fmat)
    if (!is.finite(detF) || detF <= 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    invF <- solve(Fmat)
    ll <- ll - 0.5 * (log(detF) + t(v) %*% invF %*% v)

    K <- Tmat %*% Pest %*% t(Z_i) %*% invF

    aest <- a_pred + K %*% v
    Pest <- Tmat %*% Pest %*% t(Tmat - K %*% Z_i) + Qmat

    a_f[i,]  <- as.numeric(aest)
    P_f[[i]] <- Pest
  }

  list(ll = ll, a_f = a_f, P_f = P_f, a_p = a_p, P_p = P_p)
}

CTCRW_smoother <- function(filter_out, beta1_vec, beta2_vec,
                           s1, s2, s3, delta) {

  N <- nrow(filter_out$a_f)
  a_s <- filter_out$a_f
  P_s <- filter_out$P_f

  for (i in (N-1):1) {

    b1_i <- beta1_vec[i+1]
    b2_i <- beta2_vec[i+1]

    Tmat <- makeT_R(b1_i, b2_i, delta[i+1])

    a_f_i   <- filter_out$a_f[i,]
    a_p_ip1 <- filter_out$a_p[i+1,]
    P_f_i   <- filter_out$P_f[[i]]
    P_p_ip1 <- filter_out$P_p[[i+1]]

    J <- tryCatch(P_f_i %*% t(Tmat) %*% solve(P_p_ip1), error = function(e) NULL)

    if (is.null(J)) next

    a_s[i,]  <- a_f_i + J %*% (a_s[i+1,] - a_p_ip1)
    P_s[[i]] <- P_f_i + J %*% (P_s[[i+1]] - P_p_ip1) %*% t(J)
  }

  list(a_s = a_s, P_s = P_s)
}



neg_loglikelihood <- function(params, data_aug) {

  beta1  <- exp(params["beta1"])
  beta2  <- exp(params["beta2"])
  sigma  <- exp(params["sigma"])
  sigma2 <- exp(params["sigma2"])
  tau1   <- exp(params["tau1"])
  tau2   <- exp(params["tau2"])

  y   <- as.matrix(data_aug[, c("x","y","depth")])
  hd  <- data_aug$hdop

  # hdop-scaled horizontal error, constant depth error
  # *** FIX 1: NO ARTIFICIAL ERROR FLOOR ***
  Hmat <- matrix(NA_real_, nrow(data_aug), 3)
  for (i in 1:nrow(data_aug)) {
    if (!is.na(y[i,1]) && !is.na(hd[i])) Hmat[i,1] <- (tau1 * (hd[i])^0.5)^2
    if (!is.na(y[i,2]) && !is.na(hd[i])) Hmat[i,2] <- (tau1 * (hd[i])^0.5)^2
    if (!is.na(y[i,3]))                Hmat[i,3] <- tau2^2
  }

  # use constant dt (matches simulation)
  delta <- rep(dt, nrow(data_aug))

  s1 <- sigma^2
  s2 <- sigma^2
  s3 <- sigma2^2

  beta1_vec <- rep(beta1, nrow(data_aug))
  beta2_vec <- rep(beta2, nrow(data_aug))

  has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
  first_obs <- which(has_any)[1]

  a <- c(
    ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
    ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
    ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
  )
  P <- diag(6) * 1e2

  filt <- CTCRW_filter(
    y         = y,
    Hmat      = Hmat,
    beta1_vec = beta1_vec,
    beta2_vec = beta2_vec,
    s1        = s1,
    s2        = s2,
    s3        = s3,
    delta     = delta,
    a         = a,
    P         = P
  )

  -filt$ll
}

params_start <- c(
  beta1  = log(0.5),
  beta2  = log(0.5),
  sigma  = log(10),
  sigma2 = log(10),
  tau1   = log(30),
  tau2   = log(10)
)

fit <- optim(
  par      = params_start,
  fn       = neg_loglikelihood,
  data_aug = aug,
  method   = "L-BFGS-B",
  control  = list(trace = 1, maxit = 1000)
)

p_hat <- exp(fit$par)
p_hat




beta1_hat <- p_hat["beta1"]
beta2_hat <- p_hat["beta2"]
sigma_hat <- p_hat["sigma"]
sigma2_hat <- p_hat["sigma2"]
tau1_hat <- p_hat["tau1"]
tau2_hat <- p_hat["tau2"]

y  <- as.matrix(aug[, c("x","y","depth")])
hd <- aug$hdop

Hmat <- matrix(NA_real_, nrow(aug), 3)
for (i in 1:nrow(aug)) {
  if (!is.na(y[i,1]) && !is.na(hd[i])) Hmat[i,1] <- (tau1_hat * (hd[i])^0.5)^2
  if (!is.na(y[i,2]) && !is.na(hd[i])) Hmat[i,2] <- (tau1_hat * (hd[i])^0.5)^2
  if (!is.na(y[i,3]))                Hmat[i,3] <- tau2_hat^2
}

delta <- rep(dt, nrow(aug))

s1 <- sigma_hat^2
s2 <- sigma_hat^2
s3 <- sigma2_hat^2

beta1_vec <- rep(beta1_hat, nrow(aug))
beta2_vec <- rep(beta2_hat, nrow(aug))

has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
first_obs <- which(has_any)[1]

a0 <- c(
  ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
  ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
  ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
)
P0 <- diag(6) * 1e2

filt <- CTCRW_filter(
  y         = y,
  Hmat      = Hmat,
  beta1_vec = beta1_vec,
  beta2_vec = beta2_vec,
  s1        = s1,
  s2        = s2,
  s3        = s3,
  delta     = delta,
  a         = a0,
  P         = P0
)

smth <- CTCRW_smoother(
  filter_out = filt,
  beta1_vec  = beta1_vec,
  beta2_vec  = beta2_vec,
  s1         = s1,
  s2         = s2,
  s3         = s3,
  delta      = delta
)

aug$mu_x     <- smth$a_s[,1]
aug$mu_y     <- smth$a_s[,3]
aug$mu_depth <- smth$a_s[,5]

# 2D horizontal track
xlim <- range(aug$x, na.rm = TRUE)
ylim <- range(aug$y, na.rm = TRUE)

ggplot(aug %>% arrange(Time), aes(x = x, y = y)) +
  geom_point(color = "grey70", alpha = 0.5) +
  geom_path(aes(x = mu_x, y = mu_y), color = "blue") +
  coord_equal(xlim = xlim, ylim = ylim) +
  theme_minimal() +
  labs(x = "x (m)", y = "y (m)", title = "Smoothed Horizontal Track (meters)")

# Depth vs time
ggplot(aug %>% arrange(time), aes(x = time)) +
  geom_point(aes(y = depth), color = "grey70", alpha = 0.5) +
  geom_line(aes(y = mu_depth), color = "blue", linewidth = 1) +
  theme_minimal() +
  labs(x = "Time", y = "Depth (m)", title = "Smoothed Depth Profile")

# 3D interactive plot
p_raw <- plot_ly(
  data = aug,
  x = ~x,
  y = ~y,
  z = ~depth,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 2, color = "gray", opacity = 0.4),
  name = "Observed"
)

p_smooth <- plot_ly(
  data = aug,
  x = ~mu_x,
  y = ~mu_y,
  z = ~mu_depth,
  type = "scatter3d",
  mode = "lines",
  line = list(color = "blue", width = 4),
  name = "Smoothed Track"
)

subplot(p_raw, p_smooth) %>%
  layout(
    title = "3D Track of Simulated Movement",
    scene = list(
      xaxis = list(title = "x (m)"),
      yaxis = list(title = "y (m)"),
      zaxis = list(title = "Depth (m)", autorange = "reversed")
    )
  )



########################################################
########################################################


############################################################
# Code E: 3D CTCRW simulation, filtering, smoothing, MLE
#         with known measurement error using hdop
############################################################

library(MASS)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
set.seed(123)

############################################################
# TRUE PROCESS PARAMETERS (latent CTCRW)
############################################################

beta1_true  <- 1.8   # horizontal OU damping
beta2_true  <- 0.8   # vertical OU damping
sigma_true  <- 20    # horizontal process noise SD
sigma2_true <- 10    # vertical process noise SD

s1 <- sigma_true^2
s2 <- sigma_true^2
s3 <- sigma2_true^2

# Known measurement error structure (NOT estimated)
meas_sd_xy_base   <- 30   # base SD in meters for x,y
meas_sd_depth     <- 10   # SD in meters for depth

############################################################
# LATENT CTCRW PROCESS
############################################################

N  <- 5000
dt <- 15 / (24*60)   # 15 minutes in days
time_vec <- seq(0, by = dt, length.out = N)

# State vector: (x, vx, y, vy, depth, vdepth)
X <- matrix(0, nrow = N, ncol = 6)
X[1,] <- c(0, 0, 0, 0, -50, 0)

makeT <- function(b1, b2, dt) {
  T <- matrix(0, 6, 6)
  e1 <- exp(-b1 * dt)
  e2 <- exp(-b2 * dt)
  T[1,1] <- 1; T[2,2] <- e1; T[1,2] <- (1 - e1)/b1
  T[3,3] <- 1; T[4,4] <- e1; T[3,4] <- (1 - e1)/b1
  T[5,5] <- 1; T[6,6] <- e2; T[5,6] <- (1 - e2)/b2
  T
}

makeQ <- function(b1, b2, s1, s2, s3, dt) {
  e1  <- exp(-b1 * dt)
  e2  <- exp(-2*b1*dt)
  q11_1 <- (dt - 2*(1-e1)/b1 + (1-e2)/(2*b1)) / b1^2
  q13_1 <- ((1-e1) - (1-e2)/2) / b1^2
  q33_1 <- (1-e2)/(2*b1)

  e1v  <- exp(-b2 * dt)
  e2v  <- exp(-2*b2*dt)
  q11_2 <- (dt - 2*(1-e1v)/b2 + (1-e2v)/(2*b2)) / b2^2
  q13_2 <- ((1-e1v) - (1-e2v)/2) / b2^2
  q33_2 <- (1-e2v)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

Tmat <- makeT(beta1_true, beta2_true, dt)
Qmat <- makeQ(beta1_true, beta2_true, s1, s2, s3, dt)

for (i in 2:N) {
  X[i,] <- Tmat %*% X[i-1,] + MASS::mvrnorm(1, rep(0,6), Qmat)
}

############################################################
# OBSERVATIONS WITH MEASUREMENT ERROR + hdop
############################################################

obs_type <- rbinom(N, 1, 0.7)   # 70% depth-only, 30% xy-only

obs_x     <- rep(NA, N)
obs_y     <- rep(NA, N)
obs_depth <- rep(NA, N)
hdop      <- rep(NA, N)

for (i in 1:N) {
  if (obs_type[i] == 1) {
    # depth-only observation
    obs_depth[i] <- X[i,5] + rnorm(1, 0, meas_sd_depth)
    hdop[i]      <- NA
  } else {
    # xy-only observation
    obs_x[i] <- X[i,1] + rnorm(1, 0, meas_sd_xy_base)
    obs_y[i] <- X[i,3] + rnorm(1, 0, meas_sd_xy_base)
    hdop[i]  <- runif(1, 1, 25)  # hdop between 1 and 25
  }
}

sim_data <- data.frame(
  time  = ymd_hms("2020-01-01 00:00:00") + time_vec*86400,
  x     = obs_x,
  y     = obs_y,
  depth = obs_depth,
  hdop  = hdop
)

aug <- sim_data %>%
  mutate(
    Time = as.numeric(difftime(time, min(time), units = "days")) + 1,
    hasObs = !is.na(x) | !is.na(y) | !is.na(depth),
    orig_index = seq_len(n())
  )

summary(aug[, c("x","y","depth","hdop","Time")])

############################################################
# MODEL MATRICES FOR IRREGULAR STEPS
############################################################

makeT_R <- function(b1, b2, delta) {
  ebd1 <- exp(-b1 * delta)
  ebd2 <- exp(-b2 * delta)
  T <- matrix(0, 6, 6)
  T[1,1] <- 1; T[2,2] <- ebd1; T[1,2] <- (1 - ebd1)/b1
  T[3,3] <- 1; T[4,4] <- ebd1; T[3,4] <- (1 - ebd1)/b1
  T[5,5] <- 1; T[6,6] <- ebd2; T[5,6] <- (1 - ebd2)/b2
  T
}

makeQ_R <- function(b1, b2, s1, s2, s3, delta) {
  ebd1  <- exp(-b1 * delta)
  e2bd1 <- exp(-2*b1*delta)
  q11_1 <- (delta - 2*(1-ebd1)/b1 + (1-e2bd1)/(2*b1)) / b1^2
  q13_1 <- ((1-ebd1) - (1-e2bd1)/2) / b1^2
  q33_1 <- (1-e2bd1)/(2*b1)

  ebd2  <- exp(-b2 * delta)
  e2bd2 <- exp(-2*b2*delta)
  q11_2 <- (delta - 2*(1-ebd2)/b2 + (1-e2bd2)/(2*b2)) / b2^2
  q13_2 <- ((1-ebd2) - (1-e2bd2)/2) / b2^2
  q33_2 <- (1-e2bd2)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

############################################################
# FILTER (with known measurement error via hdop)
############################################################

CTCRW_filter <- function(y, Hmat, beta1_vec, beta2_vec,
                         s1, s2, s3, delta, a, P) {

  N <- nrow(y)

  Z_full <- matrix(0, 3, 6)
  Z_full[1,1] <- 1
  Z_full[2,3] <- 1
  Z_full[3,5] <- 1

  a_f <- matrix(NA, N, 6)
  P_f <- vector("list", N)
  a_p <- matrix(NA, N, 6)
  P_p <- vector("list", N)

  aest <- a
  Pest <- P
  ll <- 0

  for (i in 1:N) {

    b1_i <- beta1_vec[i]
    b2_i <- beta2_vec[i]

    Tmat <- makeT_R(b1_i, b2_i, delta[i])
    Qmat <- makeQ_R(b1_i, b2_i, s1, s2, s3, delta[i])

    a_pred <- Tmat %*% aest
    P_pred <- Tmat %*% Pest %*% t(Tmat) + Qmat

    a_p[i,]  <- as.numeric(a_pred)
    P_p[[i]] <- P_pred

    obs_idx <- which(!is.na(y[i, ]))

    if (length(obs_idx) == 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    Z_i <- Z_full[obs_idx, , drop = FALSE]
    H_i <- diag(Hmat[i, obs_idx], length(obs_idx))

    v <- y[i, obs_idx] - Z_i %*% aest
    Fmat <- Z_i %*% Pest %*% t(Z_i) + H_i

    detF <- det(Fmat)
    if (!is.finite(detF) || detF <= 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    invF <- solve(Fmat)
    ll <- ll - 0.5 * (log(detF) + t(v) %*% invF %*% v)

    K <- Tmat %*% Pest %*% t(Z_i) %*% invF

    aest <- a_pred + K %*% v
    Pest <- Tmat %*% Pest %*% t(Tmat - K %*% Z_i) + Qmat

    a_f[i,]  <- as.numeric(aest)
    P_f[[i]] <- Pest
  }

  list(ll = ll, a_f = a_f, P_f = P_f, a_p = a_p, P_p = P_p)
}

############################################################
# SMOOTHER
############################################################

CTCRW_smoother <- function(filter_out, beta1_vec, beta2_vec,
                           s1, s2, s3, delta) {

  N <- nrow(filter_out$a_f)
  a_s <- filter_out$a_f
  P_s <- filter_out$P_f

  for (i in (N-1):1) {

    b1_i <- beta1_vec[i+1]
    b2_i <- beta2_vec[i+1]

    Tmat <- makeT_R(b1_i, b2_i, delta[i+1])

    a_f_i   <- filter_out$a_f[i,]
    a_p_ip1 <- filter_out$a_p[i+1,]
    P_f_i   <- filter_out$P_f[[i]]
    P_p_ip1 <- filter_out$P_p[[i+1]]

    J <- tryCatch(P_f_i %*% t(Tmat) %*% solve(P_p_ip1), error = function(e) NULL)

    if (is.null(J)) next

    a_s[i,]  <- a_f_i + J %*% (a_s[i+1,] - a_p_ip1)
    P_s[[i]] <- P_f_i + J %*% (P_s[[i+1]] - P_p_ip1) %*% t(J)
  }

  list(a_s = a_s, P_s = P_s)
}

############################################################
# NEGATIVE LOG-LIKELIHOOD (beta1, beta2, sigma, sigma2 only)
############################################################

neg_loglikelihood <- function(params, data_aug) {

  beta1  <- exp(params["beta1"])
  beta2  <- exp(params["beta2"])
  sigma  <- exp(params["sigma"])
  sigma2 <- exp(params["sigma2"])

  y   <- as.matrix(data_aug[, c("x","y","depth")])
  hd  <- data_aug$hdop

  # Known measurement error: hdop-scaled for x,y, constant for depth
  Hmat <- matrix(NA_real_, nrow(data_aug), 3)
  for (i in 1:nrow(data_aug)) {
    if (!is.na(y[i,1]) && !is.na(hd[i])) {
      Hmat[i,1] <- (meas_sd_xy_base * sqrt(hd[i]))^2
    }
    if (!is.na(y[i,2]) && !is.na(hd[i])) {
      Hmat[i,2] <- (meas_sd_xy_base * sqrt(hd[i]))^2
    }
    if (!is.na(y[i,3])) {
      Hmat[i,3] <- meas_sd_depth^2
    }
  }

  delta <- rep(dt, nrow(data_aug))

  s1 <- sigma^2
  s2 <- sigma^2
  s3 <- sigma2^2

  beta1_vec <- rep(beta1, nrow(data_aug))
  beta2_vec <- rep(beta2, nrow(data_aug))

  has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
  first_obs <- which(has_any)[1]

  a <- c(
    ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
    ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
    ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
  )
  P <- diag(6) * 1e2

  filt <- CTCRW_filter(
    y         = y,
    Hmat      = Hmat,
    beta1_vec = beta1_vec,
    beta2_vec = beta2_vec,
    s1        = s1,
    s2        = s2,
    s3        = s3,
    delta     = delta,
    a         = a,
    P         = P
  )

  -filt$ll
}

############################################################
# PARAMETER ESTIMATION
############################################################

params_start <- c(
  beta1  = log(0.5),
  beta2  = log(0.5),
  sigma  = log(10),
  sigma2 = log(10)
)

fit <- optim(
  par      = params_start,
  fn       = neg_loglikelihood,
  data_aug = aug,
  method   = "L-BFGS-B",
  control  = list(trace = 1, maxit = 1000)
)

p_hat <- exp(fit$par)
p_hat

beta1_hat  <- p_hat["beta1"]
beta2_hat  <- p_hat["beta2"]
sigma_hat  <- p_hat["sigma"]
sigma2_hat <- p_hat["sigma2"]

############################################################
# FILTERING AND SMOOTHING WITH ESTIMATED PARAMETERS
############################################################

y  <- as.matrix(aug[, c("x","y","depth")])
hd <- aug$hdop

Hmat <- matrix(NA_real_, nrow(aug), 3)
for (i in 1:nrow(aug)) {
  if (!is.na(y[i,1]) && !is.na(hd[i])) {
    Hmat[i,1] <- (meas_sd_xy_base * sqrt(hd[i]))^2
  }
  if (!is.na(y[i,2]) && !is.na(hd[i])) {
    Hmat[i,2] <- (meas_sd_xy_base * sqrt(hd[i]))^2
  }
  if (!is.na(y[i,3])) {
    Hmat[i,3] <- meas_sd_depth^2
  }
}

delta <- rep(dt, nrow(aug))

s1 <- sigma_hat^2
s2 <- sigma_hat^2
s3 <- sigma2_hat^2

beta1_vec <- rep(beta1_hat, nrow(aug))
beta2_vec <- rep(beta2_hat, nrow(aug))

has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
first_obs <- which(has_any)[1]

a0 <- c(
  ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
  ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
  ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
)
P0 <- diag(6) * 1e2

filt <- CTCRW_filter(
  y         = y,
  Hmat      = Hmat,
  beta1_vec = beta1_vec,
  beta2_vec = beta2_vec,
  s1        = s1,
  s2        = s2,
  s3        = s3,
  delta     = delta,
  a         = a0,
  P         = P0
)

smth <- CTCRW_smoother(
  filter_out = filt,
  beta1_vec  = beta1_vec,
  beta2_vec  = beta2_vec,
  s1         = s1,
  s2         = s2,
  s3         = s3,
  delta      = delta
)

aug$mu_x     <- smth$a_s[,1]
aug$mu_y     <- smth$a_s[,3]
aug$mu_depth <- smth$a_s[,5]

############################################################
# PLOTS
############################################################

# 2D horizontal track
xlim <- range(aug$x, na.rm = TRUE)
ylim <- range(aug$y, na.rm = TRUE)

ggplot(aug %>% arrange(Time), aes(x = x, y = y)) +
  geom_point(color = "grey70", alpha = 0.5) +
  geom_path(aes(x = mu_x, y = mu_y), color = "blue") +
  coord_equal(xlim = xlim, ylim = ylim) +
  theme_minimal() +
  labs(x = "x (m)", y = "y (m)", title = "Smoothed Horizontal Track (meters)")

# Depth vs time
ggplot(aug %>% arrange(time), aes(x = time)) +
  geom_point(aes(y = depth), color = "grey70", alpha = 0.5) +
  geom_line(aes(y = mu_depth), color = "blue", linewidth = 1) +
  theme_minimal() +
  labs(x = "Time", y = "Depth (m)", title = "Smoothed Depth Profile")

# 3D interactive plot
p_raw <- plot_ly(
  data = aug,
  x = ~x,
  y = ~y,
  z = ~depth,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 2, color = "gray", opacity = 0.4),
  name = "Observed"
)

p_smooth <- plot_ly(
  data = aug,
  x = ~mu_x,
  y = ~mu_y,
  z = ~mu_depth,
  type = "scatter3d",
  mode = "lines",
  line = list(color = "blue", width = 4),
  name = "Smoothed Track"
)

subplot(p_raw, p_smooth) %>%
  layout(
    title = "3D Track of Simulated Movement (Code E)",
    scene = list(
      xaxis = list(title = "x (m)"),
      yaxis = list(title = "y (m)"),
      zaxis = list(title = "Depth (m)", autorange = "reversed")
    )
  )




##############################
##############################









library(MASS)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
set.seed(123)


# TRUE PARAMETERS
beta1_true  <- 1.8     # horizontal OU damping
beta2_true  <- 0.8     # vertical OU damping
sigma_true  <- 20      # horizontal process noise SD
sigma2_true <- 10      # vertical process noise SD

s1 <- sigma_true^2
s2 <- sigma_true^2
s3 <- sigma2_true^2

# LATENT CTCRW PROCESS
N  <- 5000
dt <- 15 / (24*60)   # 15 minutes in days
time_vec <- seq(0, by = dt, length.out = N)

# State vector: (x, vx, y, vy, depth, vdepth)
X <- matrix(0, nrow = N, ncol = 6)
X[1,] <- c(0, 0, 0, 0, -50, 0)

makeT <- function(b1, b2, dt) {
  T <- matrix(0, 6, 6)
  e1 <- exp(-b1 * dt)
  e2 <- exp(-b2 * dt)
  T[1,1] <- 1; T[2,2] <- e1; T[1,2] <- (1 - e1)/b1
  T[3,3] <- 1; T[4,4] <- e1; T[3,4] <- (1 - e1)/b1
  T[5,5] <- 1; T[6,6] <- e2; T[5,6] <- (1 - e2)/b2
  T
}

makeQ <- function(b1, b2, s1, s2, s3, dt) {
  e1  <- exp(-b1 * dt)
  e2  <- exp(-2*b1*dt)
  q11_1 <- (dt - 2*(1-e1)/b1 + (1-e2)/(2*b1)) / b1^2
  q13_1 <- ((1-e1) - (1-e2)/2) / b1^2
  q33_1 <- (1-e2)/(2*b1)

  e1v  <- exp(-b2 * dt)
  e2v  <- exp(-2*b2*dt)
  q11_2 <- (dt - 2*(1-e1v)/b2 + (1-e2v)/(2*b2)) / b2^2
  q13_2 <- ((1-e1v) - (1-e2v)/2) / b2^2
  q33_2 <- (1-e2v)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

Tmat <- makeT(beta1_true, beta2_true, dt)
Qmat <- makeQ(beta1_true, beta2_true, s1, s2, s3, dt)

for (i in 2:N) {
  X[i,] <- Tmat %*% X[i-1,] + MASS::mvrnorm(1, rep(0,6), Qmat)
}



# OBSERVATIONS WITH MEASUREMENT ERROR + hdop
obs_type <- rbinom(N, 1, 0.7)   # 70% depth-only, 30% xy-only

obs_x     <- rep(NA, N)
obs_y     <- rep(NA, N)
obs_depth <- rep(NA, N)
hdop      <- rep(NA, N)

# "True" measurement error model used in simulation:
# horizontal SD: sd_xy(hdop) = sqrt( var0_xy + var1_xy * hdop )
# depth SD: constant sd_depth
var0_xy   <- 10^2      # base variance (m^2)
var1_xy   <- 5^2       # per-unit hdop variance (m^2 per hdop)
sd_depth  <- 10        # depth SD (m)

sd_xy_fun <- function(h) {
  sqrt(var0_xy + var1_xy * h)
}

for (i in 1:N) {
  if (obs_type[i] == 1) {
    # depth-only observation
    obs_depth[i] <- X[i,5] + rnorm(1, 0, sd_depth)
    hdop[i]      <- NA
  } else {
    # xy-only observation
    hdop[i]  <- runif(1, 1, 25)  # hdop between 1 and 25
    sd_xy_i  <- sd_xy_fun(hdop[i])
    obs_x[i] <- X[i,1] + rnorm(1, 0, sd_xy_i)
    obs_y[i] <- X[i,3] + rnorm(1, 0, sd_xy_i)
  }
}

sim_data <- data.frame(
  time  = ymd_hms("2020-01-01 00:00:00") + time_vec*86400,
  x     = obs_x,
  y     = obs_y,
  depth = obs_depth,
  hdop  = hdop
)

aug <- sim_data %>%
  mutate(
    Time = as.numeric(difftime(time, min(time), units = "days")) + 1,
    hasObs = !is.na(x) | !is.na(y) | !is.na(depth),
    orig_index = seq_len(n())
  )

summary(aug[, c("x","y","depth","hdop","Time")])






makeT_R <- function(b1, b2, delta) {
  ebd1 <- exp(-b1 * delta)
  ebd2 <- exp(-b2 * delta)
  T <- matrix(0, 6, 6)
  T[1,1] <- 1; T[2,2] <- ebd1; T[1,2] <- (1 - ebd1)/b1
  T[3,3] <- 1; T[4,4] <- ebd1; T[3,4] <- (1 - ebd1)/b1
  T[5,5] <- 1; T[6,6] <- ebd2; T[5,6] <- (1 - ebd2)/b2
  T
}

makeQ_R <- function(b1, b2, s1, s2, s3, delta) {
  ebd1  <- exp(-b1 * delta)
  e2bd1 <- exp(-2*b1*delta)
  q11_1 <- (delta - 2*(1-ebd1)/b1 + (1-e2bd1)/(2*b1)) / b1^2
  q13_1 <- ((1-ebd1) - (1-e2bd1)/2) / b1^2
  q33_1 <- (1-e2bd1)/(2*b1)

  ebd2  <- exp(-b2 * delta)
  e2bd2 <- exp(-2*b2*delta)
  q11_2 <- (delta - 2*(1-ebd2)/b2 + (1-e2bd2)/(2*b2)) / b2^2
  q13_2 <- ((1-ebd2) - (1-e2bd2)/2) / b2^2
  q33_2 <- (1-e2bd2)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}



CTCRW_filter <- function(y, Hmat, beta1_vec, beta2_vec,
                         s1, s2, s3, delta, a, P) {

  N <- nrow(y)

  Z_full <- matrix(0, 3, 6)
  Z_full[1,1] <- 1
  Z_full[2,3] <- 1
  Z_full[3,5] <- 1

  a_f <- matrix(NA, N, 6)
  P_f <- vector("list", N)
  a_p <- matrix(NA, N, 6)
  P_p <- vector("list", N)

  aest <- a
  Pest <- P
  ll <- 0

  for (i in 1:N) {

    b1_i <- beta1_vec[i]
    b2_i <- beta2_vec[i]

    Tmat <- makeT_R(b1_i, b2_i, delta[i])
    Qmat <- makeQ_R(b1_i, b2_i, s1, s2, s3, delta[i])

    a_pred <- Tmat %*% aest
    P_pred <- Tmat %*% Pest %*% t(Tmat) + Qmat

    a_p[i,]  <- as.numeric(a_pred)
    P_p[[i]] <- P_pred

    obs_idx <- which(!is.na(y[i, ]))

    if (length(obs_idx) == 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    Z_i <- Z_full[obs_idx, , drop = FALSE]
    H_i <- diag(Hmat[i, obs_idx], length(obs_idx))

    v <- y[i, obs_idx] - Z_i %*% aest
    Fmat <- Z_i %*% Pest %*% t(Z_i) + H_i

    detF <- det(Fmat)
    if (!is.finite(detF) || detF <= 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    invF <- solve(Fmat)
    ll <- ll - 0.5 * (log(detF) + t(v) %*% invF %*% v)

    K <- Tmat %*% Pest %*% t(Z_i) %*% invF

    aest <- a_pred + K %*% v
    Pest <- Tmat %*% Pest %*% t(Tmat - K %*% Z_i) + Qmat

    a_f[i,]  <- as.numeric(aest)
    P_f[[i]] <- Pest
  }

  list(ll = ll, a_f = a_f, P_f = P_f, a_p = a_p, P_p = P_p)
}


CTCRW_smoother <- function(filter_out, beta1_vec, beta2_vec,
                           s1, s2, s3, delta) {

  N <- nrow(filter_out$a_f)
  a_s <- filter_out$a_f
  P_s <- filter_out$P_f

  for (i in (N-1):1) {

    b1_i <- beta1_vec[i+1]
    b2_i <- beta2_vec[i+1]

    Tmat <- makeT_R(b1_i, b2_i, delta[i+1])

    a_f_i   <- filter_out$a_f[i,]
    a_p_ip1 <- filter_out$a_p[i+1,]
    P_f_i   <- filter_out$P_f[[i]]
    P_p_ip1 <- filter_out$P_p[[i+1]]

    J <- tryCatch(P_f_i %*% t(Tmat) %*% solve(P_p_ip1), error = function(e) NULL)

    if (is.null(J)) next

    a_s[i,]  <- a_f_i + J %*% (a_s[i+1,] - a_p_ip1)
    P_s[[i]] <- P_f_i + J %*% (P_s[[i+1]] - P_p_ip1) %*% t(J)
  }

  list(a_s = a_s, P_s = P_s)
}





# Build known measurement-error matrix Hmat from hdop
build_Hmat <- function(data_aug, var0_xy, var1_xy, sd_depth) {
  y  <- as.matrix(data_aug[, c("x","y","depth")])
  hd <- data_aug$hdop

  Hmat <- matrix(NA_real_, nrow(data_aug), 3)

  for (i in 1:nrow(data_aug)) {
    if (!is.na(hd[i])) {
      var_xy_i <- var0_xy + var1_xy * hd[i]
      if (!is.na(y[i,1])) Hmat[i,1] <- var_xy_i
      if (!is.na(y[i,2])) Hmat[i,2] <- var_xy_i
    }
    if (!is.na(y[i,3])) {
      Hmat[i,3] <- sd_depth^2
    }
  }

  Hmat
}

neg_loglikelihood <- function(params, data_aug) {

  beta1  <- exp(params["beta1"])
  beta2  <- exp(params["beta2"])
  sigma  <- exp(params["sigma"])
  sigma2 <- exp(params["sigma2"])

  y <- as.matrix(data_aug[, c("x","y","depth")])

  # known measurement error model (same structure as simulation)
  var0_xy  <- 10^2
  var1_xy  <- 5^2
  sd_depth <- 10

  Hmat <- build_Hmat(data_aug, var0_xy, var1_xy, sd_depth)

  delta <- rep(dt, nrow(data_aug))

  s1 <- sigma^2
  s2 <- sigma^2
  s3 <- sigma2^2

  beta1_vec <- rep(beta1, nrow(data_aug))
  beta2_vec <- rep(beta2, nrow(data_aug))

  has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
  first_obs <- which(has_any)[1]

  a <- c(
    ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
    ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
    ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
  )
  P <- diag(6) * 1e2

  filt <- CTCRW_filter(
    y         = y,
    Hmat      = Hmat,
    beta1_vec = beta1_vec,
    beta2_vec = beta2_vec,
    s1        = s1,
    s2        = s2,
    s3        = s3,
    delta     = delta,
    a         = a,
    P         = P
  )

  -filt$ll
}

params_start <- c(
  beta1  = log(0.5),
  beta2  = log(0.5),
  sigma  = log(10),
  sigma2 = log(10)
)

fit <- optim(
  par      = params_start,
  fn       = neg_loglikelihood,
  data_aug = aug,
  method   = "L-BFGS-B",
  control  = list(trace = 1, maxit = 1000)
)

p_hat <- exp(fit$par)
p_hat


beta1_hat <- p_hat["beta1"]
beta2_hat <- p_hat["beta2"]
sigma_hat <- p_hat["sigma"]
sigma2_hat <- p_hat["sigma2"]

y  <- as.matrix(aug[, c("x","y","depth")])

var0_xy  <- 10^2
var1_xy  <- 5^2
sd_depth <- 10

Hmat <- build_Hmat(aug, var0_xy, var1_xy, sd_depth)

delta <- rep(dt, nrow(aug))

s1 <- sigma_hat^2
s2 <- sigma_hat^2
s3 <- sigma2_hat^2

beta1_vec <- rep(beta1_hat, nrow(aug))
beta2_vec <- rep(beta2_hat, nrow(aug))

has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
first_obs <- which(has_any)[1]

a0 <- c(
  ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
  ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
  ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
)
P0 <- diag(6) * 1e2

filt <- CTCRW_filter(
  y         = y,
  Hmat      = Hmat,
  beta1_vec = beta1_vec,
  beta2_vec = beta2_vec,
  s1        = s1,
  s2        = s2,
  s3        = s3,
  delta     = delta,
  a         = a0,
  P         = P0
)

smth <- CTCRW_smoother(
  filter_out = filt,
  beta1_vec  = beta1_vec,
  beta2_vec  = beta2_vec,
  s1         = s1,
  s2         = s2,
  s3         = s3,
  delta      = delta
)

aug$mu_x     <- smth$a_s[,1]
aug$mu_y     <- smth$a_s[,3]
aug$mu_depth <- smth$a_s[,5]




# 2D horizontal track
xlim <- range(aug$x, na.rm = TRUE)
ylim <- range(aug$y, na.rm = TRUE)

ggplot(aug %>% arrange(Time), aes(x = x, y = y)) +
  geom_point(color = "grey70", alpha = 0.5) +
  geom_path(aes(x = mu_x, y = mu_y), color = "blue") +
  coord_equal(xlim = xlim, ylim = ylim) +
  theme_minimal() +
  labs(x = "x (m)", y = "y (m)", title = "Smoothed Horizontal Track (meters)")

# Depth vs time
ggplot(aug %>% arrange(time), aes(x = time)) +
  geom_point(aes(y = depth), color = "grey70", alpha = 0.5) +
  geom_line(aes(y = mu_depth), color = "blue", linewidth = 1) +
  theme_minimal() +
  labs(x = "Time", y = "Depth (m)", title = "Smoothed Depth Profile")

# 3D interactive plot
p_raw <- plot_ly(
  data = aug,
  x = ~x,
  y = ~y,
  z = ~depth,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 2, color = "gray", opacity = 0.4),
  name = "Observed"
)

p_smooth <- plot_ly(
  data = aug,
  x = ~mu_x,
  y = ~mu_y,
  z = ~mu_depth,
  type = "scatter3d",
  mode = "lines",
  line = list(color = "blue", width = 4),
  name = "Smoothed Track"
)

subplot(p_raw, p_smooth) %>%
  layout(
    title = "3D Track of Simulated Movement",
    scene = list(
      xaxis = list(title = "x (m)"),
      yaxis = list(title = "y (m)"),
      zaxis = list(title = "Depth (m)", autorange = "reversed")
    )
  )





###############################
###############################





library(MASS)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
set.seed(123)

# Define TRUE CTCRW parameters.
beta1_true  <- 2.8     # horizontal OU damping
beta2_true  <- 0.8     # vertical OU damping
sigma_true  <- 30      # horizontal process noise SD
sigma2_true <- 10      # vertical process noise SD

# computing variances inside the Q matrix.
s1 <- sigma_true^2
s2 <- sigma_true^2
s3 <- sigma2_true^2

# Set up time grid.
N  <- 5000
dt <- 15 / (24*60)   # 15 minutes in days
# vector of time stamps.
time_vec <- seq(0, by = dt, length.out = N)

# Initialize latent state vector: (x, vx, y, vy, depth, vdepth)
X <- matrix(0, nrow = N, ncol = 6)
X[1,] <- c(0, 0, 0, 0, -50, 0)

# Define T matrix.
makeT <- function(b1, b2, dt) {
  T <- matrix(0, 6, 6)
  e1 <- exp(-b1 * dt)
  e2 <- exp(-b2 * dt)
  T[1,1] <- 1; T[2,2] <- e1; T[1,2] <- (1 - e1)/b1
  T[3,3] <- 1; T[4,4] <- e1; T[3,4] <- (1 - e1)/b1
  T[5,5] <- 1; T[6,6] <- e2; T[5,6] <- (1 - e2)/b2
  T
}

# Define Q matrix.
makeQ <- function(b1, b2, s1, s2, s3, dt) {
  e1  <- exp(-b1 * dt)
  e2  <- exp(-2*b1*dt)
  q11_1 <- (dt - 2*(1-e1)/b1 + (1-e2)/(2*b1)) / b1^2
  q13_1 <- ((1-e1) - (1-e2)/2) / b1^2
  q33_1 <- (1-e2)/(2*b1)

  e1v  <- exp(-b2 * dt)
  e2v  <- exp(-2*b2*dt)
  q11_2 <- (dt - 2*(1-e1v)/b2 + (1-e2v)/(2*b2)) / b2^2
  q13_2 <- ((1-e1v) - (1-e2v)/2) / b2^2
  q33_2 <- (1-e2v)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}

Tmat <- makeT(beta1_true, beta2_true, dt)
Qmat <- makeQ(beta1_true, beta2_true, s1, s2, s3, dt)

# Simulate latent CTCRW movement.
for (i in 2:N) {
  X[i,] <- Tmat %*% X[i-1,] + MASS::mvrnorm(1, rep(0,6), Qmat)
}

# OBSERVATIONS WITH MEASUREMENT ERROR + hdop

# Simulate two types of observations: depth-only (70%), xy-only (30%).
obs_type <- rbinom(N, 1, 0.7)   # 70% depth-only, 30% xy-only

obs_x     <- rep(NA, N)
obs_y     <- rep(NA, N)
obs_depth <- rep(NA, N)
hdop      <- rep(NA, N)

# "True" measurement error model used in simulation:
# horizontal variance: var_xy(hdop) = var0_xy + var1_xy * hdop^2
# This is a quadratic hdop → variance model, which is realistic for GPS.
# Depth error is constant (10 m SD).
var0_xy   <- 10^2      # base variance (m^2)
var1_xy   <- 5^2       # per-unit hdop^2 variance (m^2 per hdop^2)
sd_depth  <- 10        # depth SD (m)

sd_xy_fun <- function(h) {
  sqrt(var0_xy + var1_xy * h^2)
}

# Build data frame (You convert simulated data into a tidy format)

for (i in 1:N) {
  if (obs_type[i] == 1) {
    # depth-only observation
    obs_depth[i] <- X[i,5] + rnorm(1, 0, sd_depth)
    hdop[i]      <- NA
  } else {
    # xy-only observation
    hdop[i]  <- runif(1, 1, 25)  # hdop between 1 and 25
    sd_xy_i  <- sd_xy_fun(hdop[i])
    obs_x[i] <- X[i,1] + rnorm(1, 0, sd_xy_i)
    obs_y[i] <- X[i,3] + rnorm(1, 0, sd_xy_i)
  }
}

sim_data <- data.frame(
  time  = ymd_hms("2020-01-01 00:00:00") + time_vec*86400,
  x     = obs_x,
  y     = obs_y,
  depth = obs_depth,
  hdop  = hdop
)

# Time = time since first observation (in days)
# hasObs = indicator for any observation
# orig_index = original row index
aug <- sim_data %>%
  mutate(
    Time = as.numeric(difftime(time, min(time), units = "days")) + 1,
    hasObs = !is.na(x) | !is.na(y) | !is.na(depth),
    orig_index = seq_len(n())
  )

summary(aug[, c("x","y","depth","hdop","Time")])



# Define T matrix (allow for time-varying dt) for filtering.
makeT_R <- function(b1, b2, delta) {
  ebd1 <- exp(-b1 * delta)
  ebd2 <- exp(-b2 * delta)
  T <- matrix(0, 6, 6)
  T[1,1] <- 1; T[2,2] <- ebd1; T[1,2] <- (1 - ebd1)/b1
  T[3,3] <- 1; T[4,4] <- ebd1; T[3,4] <- (1 - ebd1)/b1
  T[5,5] <- 1; T[6,6] <- ebd2; T[5,6] <- (1 - ebd2)/b2
  T
}

# Define Q matrix (allow for time-varying dt) for filtering.
makeQ_R <- function(b1, b2, s1, s2, s3, delta) {
  ebd1  <- exp(-b1 * delta)
  e2bd1 <- exp(-2*b1*delta)
  q11_1 <- (delta - 2*(1-ebd1)/b1 + (1-e2bd1)/(2*b1)) / b1^2
  q13_1 <- ((1-ebd1) - (1-e2bd1)/2) / b1^2
  q33_1 <- (1-e2bd1)/(2*b1)

  ebd2  <- exp(-b2 * delta)
  e2bd2 <- exp(-2*b2*delta)
  q11_2 <- (delta - 2*(1-ebd2)/b2 + (1-e2bd2)/(2*b2)) / b2^2
  q13_2 <- ((1-ebd2) - (1-e2bd2)/2) / b2^2
  q33_2 <- (1-e2bd2)/(2*b2)

  Q <- matrix(0, 6, 6)
  Q[1,1] <- s1*q11_1; Q[2,2] <- s1*q33_1; Q[1,2] <- Q[2,1] <- s1*q13_1
  Q[3,3] <- s2*q11_1; Q[4,4] <- s2*q33_1; Q[3,4] <- Q[4,3] <- s2*q13_1
  Q[5,5] <- s3*q11_2; Q[6,6] <- s3*q33_2; Q[5,6] <- Q[6,5] <- s3*q13_2
  Q
}


# Kalman filter.

CTCRW_filter <- function(y, Hmat, beta1_vec, beta2_vec,
                         s1, s2, s3, delta, a, P) {

  N <- nrow(y)

  Z_full <- matrix(0, 3, 6)
  Z_full[1,1] <- 1
  Z_full[2,3] <- 1
  Z_full[3,5] <- 1

  a_f <- matrix(NA, N, 6)
  P_f <- vector("list", N)
  a_p <- matrix(NA, N, 6)
  P_p <- vector("list", N)

  aest <- a
  Pest <- P
  ll <- 0

  for (i in 1:N) {

    b1_i <- beta1_vec[i]
    b2_i <- beta2_vec[i]

    Tmat <- makeT_R(b1_i, b2_i, delta[i])
    Qmat <- makeQ_R(b1_i, b2_i, s1, s2, s3, delta[i])

    a_pred <- Tmat %*% aest
    P_pred <- Tmat %*% Pest %*% t(Tmat) + Qmat

    a_p[i,]  <- as.numeric(a_pred)
    P_p[[i]] <- P_pred

    obs_idx <- which(!is.na(y[i, ]))

    if (length(obs_idx) == 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    Z_i <- Z_full[obs_idx, , drop = FALSE]
    H_i <- diag(Hmat[i, obs_idx], length(obs_idx))

    v <- y[i, obs_idx] - Z_i %*% aest
    Fmat <- Z_i %*% Pest %*% t(Z_i) + H_i

    detF <- det(Fmat)
    if (!is.finite(detF) || detF <= 0) {
      aest <- a_pred
      Pest <- P_pred
      a_f[i,]  <- as.numeric(aest)
      P_f[[i]] <- Pest
      next
    }

    invF <- solve(Fmat)
    ll <- ll - 0.5 * (log(detF) + t(v) %*% invF %*% v)

    K <- Tmat %*% Pest %*% t(Z_i) %*% invF

    aest <- a_pred + K %*% v
    Pest <- Tmat %*% Pest %*% t(Tmat - K %*% Z_i) + Qmat

    a_f[i,]  <- as.numeric(aest)
    P_f[[i]] <- Pest
  }

  list(ll = ll, a_f = a_f, P_f = P_f, a_p = a_p, P_p = P_p)
}


# Kalman smoother (Rauch–Tung–Striebel smoother)
# This produces the smoothed latent trajectory.

CTCRW_smoother <- function(filter_out, beta1_vec, beta2_vec,
                           s1, s2, s3, delta) {

  N <- nrow(filter_out$a_f)
  a_s <- filter_out$a_f
  P_s <- filter_out$P_f

  for (i in (N-1):1) {

    b1_i <- beta1_vec[i+1]
    b2_i <- beta2_vec[i+1]

    Tmat <- makeT_R(b1_i, b2_i, delta[i+1])

    a_f_i   <- filter_out$a_f[i,]
    a_p_ip1 <- filter_out$a_p[i+1,]
    P_f_i   <- filter_out$P_f[[i]]
    P_p_ip1 <- filter_out$P_p[[i+1]]

    J <- tryCatch(P_f_i %*% t(Tmat) %*% solve(P_p_ip1), error = function(e) NULL)

    if (is.null(J)) next

    a_s[i,]  <- a_f_i + J %*% (a_s[i+1,] - a_p_ip1)
    P_s[[i]] <- P_f_i + J %*% (P_s[[i+1]] - P_p_ip1) %*% t(J)
  }

  list(a_s = a_s, P_s = P_s)
}

### Build known measurement-error matrix Hmat from hdop (quadratic in hdop).
# The known measurement error used in the likelihood.
build_Hmat <- function(data_aug, var0_xy, var1_xy, sd_depth) {
  y  <- as.matrix(data_aug[, c("x","y","depth")])
  hd <- data_aug$hdop

  Hmat <- matrix(NA_real_, nrow(data_aug), 3)

  for (i in 1:nrow(data_aug)) {
    if (!is.na(hd[i])) {
      var_xy_i <- var0_xy + var1_xy * hd[i]^2
      if (!is.na(y[i,1])) Hmat[i,1] <- var_xy_i
      if (!is.na(y[i,2])) Hmat[i,2] <- var_xy_i
    }
    if (!is.na(y[i,3])) {
      Hmat[i,3] <- sd_depth^2
    }
  }

  Hmat
}

# Negative log-likelihood.
# Converts parameters from log-scale, Builds Hmat, Runs the filter, Returns negative log-likelihood.
neg_loglikelihood <- function(params, data_aug) {

  beta1  <- exp(params["beta1"])
  beta2  <- exp(params["beta2"])
  sigma  <- exp(params["sigma"])
  sigma2 <- exp(params["sigma2"])

  y <- as.matrix(data_aug[, c("x","y","depth")])

  # known measurement error model (same structure as simulation)
  var0_xy  <- 10^2
  var1_xy  <- 5^2
  sd_depth <- 10

  Hmat <- build_Hmat(data_aug, var0_xy, var1_xy, sd_depth)

  delta <- rep(dt, nrow(data_aug))

  s1 <- sigma^2
  s2 <- sigma^2
  s3 <- sigma2^2

  beta1_vec <- rep(beta1, nrow(data_aug))
  beta2_vec <- rep(beta2, nrow(data_aug))

  has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
  first_obs <- which(has_any)[1]

  a <- c(
    ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
    ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
    ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
  )
  P <- diag(6) * 1e2

  filt <- CTCRW_filter(
    y         = y,
    Hmat      = Hmat,
    beta1_vec = beta1_vec,
    beta2_vec = beta2_vec,
    s1        = s1,
    s2        = s2,
    s3        = s3,
    delta     = delta,
    a         = a,
    P         = P
  )

  -filt$ll
}

params_start <- c(
  beta1  = log(0.5),
  beta2  = log(0.5),
  sigma  = log(10),
  sigma2 = log(10)
)

# Optimization.
# Estimate beta1, beta2, sigma1, sigma2.
fit <- optim(
  par      = params_start,
  fn       = neg_loglikelihood,
  data_aug = aug,
  method   = "L-BFGS-B",
  control  = list(trace = 1, maxit = 1000)
)

p_hat <- exp(fit$par)
p_hat



# Run filter + smoother with estimated parameters
# You rebuild: Hmat, T and Q, initial state
# Then run: CTCRW_filter(), CTCRW_smoother()
# This produces: mu_x, mu_y, mu_depth (The smoothed latent path)

beta1_hat <- p_hat["beta1"]
beta2_hat <- p_hat["beta2"]
sigma_hat <- p_hat["sigma"]
sigma2_hat <- p_hat["sigma2"]

y  <- as.matrix(aug[, c("x","y","depth")])

var0_xy  <- 10^2
var1_xy  <- 5^2
sd_depth <- 10

Hmat <- build_Hmat(aug, var0_xy, var1_xy, sd_depth)

delta <- rep(dt, nrow(aug))

s1 <- sigma_hat^2
s2 <- sigma_hat^2
s3 <- sigma2_hat^2

beta1_vec <- rep(beta1_hat, nrow(aug))
beta2_vec <- rep(beta2_hat, nrow(aug))

has_any <- !is.na(y[,1]) | !is.na(y[,2]) | !is.na(y[,3])
first_obs <- which(has_any)[1]

a0 <- c(
  ifelse(is.na(y[first_obs,1]), 0, y[first_obs,1]), 0,
  ifelse(is.na(y[first_obs,2]), 0, y[first_obs,2]), 0,
  ifelse(is.na(y[first_obs,3]), 0, y[first_obs,3]), 0
)
P0 <- diag(6) * 1e2

filt <- CTCRW_filter(
  y         = y,
  Hmat      = Hmat,
  beta1_vec = beta1_vec,
  beta2_vec = beta2_vec,
  s1        = s1,
  s2        = s2,
  s3        = s3,
  delta     = delta,
  a         = a0,
  P         = P0
)

smth <- CTCRW_smoother(
  filter_out = filt,
  beta1_vec  = beta1_vec,
  beta2_vec  = beta2_vec,
  s1         = s1,
  s2         = s2,
  s3         = s3,
  delta      = delta
)

aug$mu_x     <- smth$a_s[,1]
aug$mu_y     <- smth$a_s[,3]
aug$mu_depth <- smth$a_s[,5]


# Plot results.

# 2D horizontal track
xlim <- range(aug$x, na.rm = TRUE)
ylim <- range(aug$y, na.rm = TRUE)

ggplot(aug %>% arrange(Time), aes(x = x, y = y)) +
  geom_point(color = "grey70", alpha = 0.5) +
  geom_path(aes(x = mu_x, y = mu_y), color = "blue") +
  coord_equal(xlim = xlim, ylim = ylim) +
  theme_minimal() +
  labs(x = "x (m)", y = "y (m)", title = "Smoothed Horizontal Track (meters)")

# Depth vs time
ggplot(aug %>% arrange(time), aes(x = time)) +
  geom_point(aes(y = depth), color = "grey70", alpha = 0.5) +
  geom_line(aes(y = mu_depth), color = "blue", linewidth = 1) +
  theme_minimal() +
  labs(x = "Time", y = "Depth (m)", title = "Smoothed Depth Profile")

# 3D interactive plot
p_raw <- plot_ly(
  data = aug,
  x = ~x,
  y = ~y,
  z = ~depth,
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 2, color = "gray", opacity = 0.4),
  name = "Observed"
)

p_smooth <- plot_ly(
  data = aug,
  x = ~mu_x,
  y = ~mu_y,
  z = ~mu_depth,
  type = "scatter3d",
  mode = "lines",
  line = list(color = "blue", width = 4),
  name = "Smoothed Track"
)

subplot(p_raw, p_smooth) %>%
  layout(
    title = "3D Track of Simulated Movement",
    scene = list(
      xaxis = list(title = "x (m)"),
      yaxis = list(title = "y (m)"),
      zaxis = list(title = "Depth (m)", autorange = "reversed")
    )
  )
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  




